# 🚀 Custom analysis settings
# ปิดการตรวจ warning/error จากโฟลเดอร์ test ทั้งหมด
analyzer:
  exclude:
    - test/**
  errors:
    unused_import: warning
    dead_code: warning
    unnecessary_this: info

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
